### ISSUE TITLE
Izuzetak se ne izvršava nikad

### ISSUE THREAD

**Issue by nspahic3** [nspahic3/VVS-Zadaca-1#2]
..help 

[vvs-zadaca-1] VerifikacijaIValidacijaSoftvera-Vjezbe-z1-Grupa4/Grupa 4/Cvjecara/Cvijet.cs (Lines 53-54)

```

    if (value > DateTime.Now && DateTime.Now.Year == 1000)
                    throw new FormatException("Datum branja ne može biti u budućnosti!");
```

[Open in IDE](https://api.codestream.com/c/YYWBRRTH3jxjS4ZY/Ap07obunQr6EwRNg5SLc1A?marker=6185bfc5131c0b5e6da31cdd&ide=default&src=GitHub) · [Open on GitHub](https://github.com/nspahic3/vvs-zadaca-1/blob/e05da3802608e2d4cb56a650c777522638b6b5f8/VerifikacijaIValidacijaSoftvera-Vjezbe-z1-Grupa4/Grupa 4/Cvjecara/Cvijet.cs#L53-L54)

<sup>Created from Visual Studio using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by adizdarevi1** [comment]
Ispravljeno
