### ISSUE TITLE
Nejasna metoda, uslov je uvijek ispunjen

### ISSUE THREAD

**Issue by nspahic3** [nspahic3/VVS-Zadaca-1#4]
[vvs-zadaca-1] VerifikacijaIValidacijaSoftvera-Vjezbe-z1-Grupa4/Grupa 4/Cvjecara/Cvijet.cs (Lines 76-88)

```

  public void NekaMetoda()
        {
            if (!sezonsko)
                return;

            int pocetakMjesec = 3,
                krajMjesec = 9;

            int mjesec = DateTime.Now.Month;

            if (mjesec < pocetakMjesec || mjesec > krajMjesec || mjesec == pocetakMjesec || mjesec == krajMjesec || mjesec > pocetakMjesec || mjesec < krajMjesec)
                kolicina = 0;
        }
```

[Open in IDE](https://api.codestream.com/c/YYWBRRTH3jxjS4ZY/sBnSu-yISDu5zDQkFU5kxg?marker=6186535324e9e94391f02e28&ide=default&src=GitHub) · [Open on GitHub](https://github.com/nspahic3/vvs-zadaca-1/blob/06aa90005b494e72147b28c695a7031ff208c2e7/VerifikacijaIValidacijaSoftvera-Vjezbe-z1-Grupa4/Grupa 4/Cvjecara/Cvijet.cs#L76-L88)

<sup>Created from Visual Studio using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by adizdarevi1** [comment]
Gotov
