### ISSUE TITLE
Šta uraditi s ovim?

### ISSUE THREAD

**Issue by nspahic3** [nspahic3/VVS-Zadaca-1#5]
[vvs-zadaca-1] VerifikacijaIValidacijaSoftvera-Vjezbe-z1-Grupa4/Grupa 4/Cvjecara/Buket.cs (Line 28)

```

 if (dodatak != "BLATOBRAN" && dodatak != "BLATOBRAN" && dodatak != "BLATOBRAN")
```

[Open in IDE](https://api.codestream.com/c/YYWBRRTH3jxjS4ZY/gGigx_NeSJyO8nvUZjl4xQ?marker=618665bb3ed5143c6a79b388&ide=default&src=GitHub) · [Open on GitHub](https://github.com/nspahic3/vvs-zadaca-1/blob/da5281cfe3aa387a99e1a755e1cae5ef8063082d/VerifikacijaIValidacijaSoftvera-Vjezbe-z1-Grupa4/Grupa 4/Cvjecara/Buket.cs#L28)

<sup>Created from Visual Studio using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by adizdarevi1** [comment]
GOTOVO
